### ISSUE TITLE
Multiple Streams using AioQuic

### ISSUE THREAD

**Issue by devkdas** [jmgurney/automtud#2]
hai ,

It is not an issue.
one small quick query

@jmgurney 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code you have in Github.

Sorry for raising an issue as i am unable to find your email to ask this query.

Looking forward for your reply

Thank you.

**Comment by jmgurney** [comment]
Yes, I was able to, at least on the client side of things.  I haven't tested server initiated connections.  I just tested this using the ntunnel implementation: https://www.funkthat.com/gitea/jmg/ntunnel

**Comment by devkdas** [comment]
Hai @jmgurney 

Thank you for replying back

I tried that but i am getting this below error

    ERROR: Command errored out with exit status 1:
     command: /root/p/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nkim4j45/aioquic/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nkim4j45/aioquic/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6egyskuh/install-record.txt --single-version-externally-managed --compile --install-headers /root/p/include/site/python3.8/aioquic
         cwd: /tmp/pip-install-nkim4j45/aioquic/
    Complete output (65 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/aioquic
    copying src/aioquic/about.py -> build/lib.linux-x86_64-3.8/aioquic
    copying src/aioquic/__init__.py -> build/lib.linux-x86_64-3.8/aioquic
    copying src/aioquic/buffer.py -> build/lib.linux-x86_64-3.8/aioquic
    copying src/aioquic/tls.py -> build/lib.linux-x86_64-3.8/aioquic
    creating build/lib.linux-x86_64-3.8/aioquic/asyncio
    copying src/aioquic/asyncio/protocol.py -> build/lib.linux-x86_64-3.8/aioquic/asyncio
    copying src/aioquic/asyncio/server.py -> build/lib.linux-x86_64-3.8/aioquic/asyncio
    copying src/aioquic/asyncio/__init__.py -> build/lib.linux-x86_64-3.8/aioquic/asyncio
    copying src/aioquic/asyncio/client.py -> build/lib.linux-x86_64-3.8/aioquic/asyncio
    creating build/lib.linux-x86_64-3.8/aioquic/h0
    copying src/aioquic/h0/connection.py -> build/lib.linux-x86_64-3.8/aioquic/h0
    copying src/aioquic/h0/__init__.py -> build/lib.linux-x86_64-3.8/aioquic/h0
    creating build/lib.linux-x86_64-3.8/aioquic/h3
    copying src/aioquic/h3/connection.py -> build/lib.linux-x86_64-3.8/aioquic/h3
    copying src/aioquic/h3/exceptions.py -> build/lib.linux-x86_64-3.8/aioquic/h3
    copying src/aioquic/h3/__init__.py -> build/lib.linux-x86_64-3.8/aioquic/h3
    copying src/aioquic/h3/events.py -> build/lib.linux-x86_64-3.8/aioquic/h3
    creating build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/connection.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/stream.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/packet.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/recovery.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/__init__.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/retry.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/rangeset.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/configuration.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/logger.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/events.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/crypto.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    copying src/aioquic/quic/packet_builder.py -> build/lib.linux-x86_64-3.8/aioquic/quic
    running egg_info
    creating src/aioquic.egg-info
    writing src/aioquic.egg-info/PKG-INFO
    writing dependency_links to src/aioquic.egg-info/dependency_links.txt
    writing requirements to src/aioquic.egg-info/requires.txt
    writing top-level names to src/aioquic.egg-info/top_level.txt
    writing manifest file 'src/aioquic.egg-info/SOURCES.txt'
    reading manifest file 'src/aioquic.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'src/aioquic.egg-info/SOURCES.txt'
    copying src/aioquic/_buffer.c -> build/lib.linux-x86_64-3.8/aioquic
    copying src/aioquic/_crypto.c -> build/lib.linux-x86_64-3.8/aioquic
    copying src/aioquic/py.typed -> build/lib.linux-x86_64-3.8/aioquic
    copying src/aioquic/_buffer.pyi -> build/lib.linux-x86_64-3.8/aioquic
    copying src/aioquic/_crypto.pyi -> build/lib.linux-x86_64-3.8/aioquic
    running build_ext
    building 'aioquic._buffer' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    creating build/temp.linux-x86_64-3.8/src/aioquic
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/root/p/include -I/usr/include/python3.8 -c src/aioquic/_buffer.c -o build/temp.linux-x86_64-3.8/src/aioquic/_buffer.o -std=c99
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.8/src/aioquic/_buffer.o -o build/lib.linux-x86_64-3.8/aioquic/_buffer.cpython-38-x86_64-linux-gnu.so
    building 'aioquic._crypto' extension
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/root/p/include -I/usr/include/python3.8 -c src/aioquic/_crypto.c -o build/temp.linux-x86_64-3.8/src/aioquic/_crypto.o -std=c99
    src/aioquic/_crypto.c:4:10: fatal error: openssl/err.h: No such file or directory
        4 | #include <openssl/err.h>
          |          ^~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/p/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nkim4j45/aioquic/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nkim4j45/aioquic/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6egyskuh/install-record.txt --single-version-externally-managed --compile --install-headers /root/p/include/site/python3.8/aioquic Check the logs for full command output.


Could you please confirm were you  also using Linux where you have created multiple streams in a single connection using AIOQUIC.

I am currently using "Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-113-generic x86_64)","Python 3.8.10" .

Could you please help to create a multiple streams in single connection using Aioquic(https://github.com/aiortc/aioquic) on Linux terminal.

any idea How can we acheive creating mulyiple streams in a single connection using Aioquic(https://github.com/aiortc/aioquic) on Linux terminal.

Thank you.
@Karthikdasari0423
